name: "Hello Actions"
description: "Greet someone"
author: "octocat@github.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "ChrisB"
  host:
    description: 'SSH address'
    required: true
  remote:
    description: 'Remote dir path'
    required: true
  port:
    description: 'SSH Port'
    required: false
    default: 22
  user:
    description: 'SSH User name'
    required: true
  key:
    description: 'Private key'
    required: true

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
